In [1]:
import numpy as np

# Important Functions to remember

https://levelup.gitconnected.com/50-numpy-functions-you-really-needed-for-data-science-fa09e8eb0cf0"

In [8]:
np.empty(2,dtype='int' ,order='C')

array([0, 0])

In [20]:
ar = np.eye(3,3, order='F')

In [24]:
ar[0][0]

1.0

In [28]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [33]:
np.arange(1, 10, .2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [36]:
np.linspace(2.0, 3.0, num=20)

array([2.        , 2.05263158, 2.10526316, 2.15789474, 2.21052632,
       2.26315789, 2.31578947, 2.36842105, 2.42105263, 2.47368421,
       2.52631579, 2.57894737, 2.63157895, 2.68421053, 2.73684211,
       2.78947368, 2.84210526, 2.89473684, 2.94736842, 3.        ])

In [38]:
np.shape(ar)

(3, 3)

In [52]:
np.sort(np.array([1,2,3,4,5,6,7,8,9]))


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
ar=np.array([1,2,3,4,5,6,7,8,9])
np.ndim(ar)

1

In [58]:
##17. Digitize

a = np.array([-0.9, 0.5, 0.9, 1, 1.2, 1.4, 3.6, 4.7, 5.3])
bins = np.array([0,1,2,3])
np.digitize(a,bins)

array([0, 1, 1, 2, 2, 2, 4, 4, 4], dtype=int64)

In [59]:
a = np.array([[2, 4, 6], [4, 8, 12]])

In [60]:
a

array([[ 2,  4,  6],
       [ 4,  8, 12]])

In [63]:
np.std(a, axis=0)

array([1., 2., 3.])